# yaml-language-server: $schema=https://withsecrets.com/ws.schema.json
---
default:
  provider: insert_provider_here
  project: insert_project_id_here
  env:
    YOUR_ENV_VARIABLE:
      value: "insert_value_here"
    YOUR_SECRET_ENV_VARIABLE:
      secret-key: "insert_secret_key_here"
